services:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - backend
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

  api2:
    <<: *api
    expose:
      - "8080"

  postgres:
    image: postgres:17.2
    hostname: postgres
    expose:
      - "5432"
    networks:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api2
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres-data:
    driver: local