services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - 'postgres'
        env_file:
            - .env
    postgres:
        image: postgres:17.2
        hostname: postgres
        ports:
          - '5432:5432'
        env_file:
          - .env