info:
  contact: {}
paths:
  /register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Register User
      tags:
      - user
  /user/:user_id/follow:
    patch:
      responses: {}
      summary: Follow new User
      tags:
      - user
  /user/:user_id/unfollow:
    patch:
      responses: {}
      summary: Unfollow an User
      tags:
      - user
swagger: "2.0"
